tasks:
  - init: pushd /tmp && rm -rf mocca && git clone --branch mocca-1.3.30  https://git.egiz.gv.at/git/mocca && cd /tmp/mocca && sed -i 's/http:\/\/repo1\.maven\.org/https:\/\/repo1\.maven\.org/g' pom.xml && mvn validate && mvn install -DskipTests && popd && mvn install -DskipTests
image:
  file: .gitpod.Dockerfile
